[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "vincisex"
version = "0.1.6"
description = "Python utility and cryptography library"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Vincent" }
]

dependencies = [
    "cryptography>=45.0.0",
    "qrcode",
    "browser_cookie3"
]

[tool.setuptools.packages.find]
where = ["src"]